spring:
  config:
    activate:
      on-profile: prod-redis
  data:
    redis:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
      port: ${REDIS_PORT}
      host: ${REDIS_HOST_DEPLOY}
      password: ${REDIS_PASSWORD}