spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    group:
      dev:
        - dev-mysql
        - dev-token
        - dev-redis
        - dev-oauth
        - dev-judge
        - dev-batch
      prod:
        - prod-mysql
        - prod-token
        - prod-redis
        - prod-oauth
        - prod-judge
    active: ${SPRING_PROFILES_ACTIVE}