spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    group:
      dev:
        - dev-mysql
        - dev-token
        - dev-redis
        - dev-oauth
      prod:
        - prod-mysql
        - prod-token
        - prod-redis
    active: ${SPRING_PROFILES_ACTIVE}