server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: ${SERVER_PORT}
spring:
  config:
    activate:
      on-profile: prod-mysql
  datasource:
    url: "jdbc:mysql://${PROD_MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?autoReconnect=true&useUnicode=true&serverTimezone=Asia/Seoul"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false

