spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    group:
      dev:
        - dev-mysql
        - dev-token
        - dev-redis
        - dev-oauth
        - dev-judge
        - dev-openvidu
      prod:
        - prod-mysql
        - prod-token
        - prod-redis
        - prod-oauth
        - prod-judge
        - prod-openvidu
    active: ${SPRING_PROFILES_ACTIVE}