spring:
  config:
    activate:
      on-profile: prod-openvidu
openvidu:
  url: ${OPENVIDU_URL}
  secret: ${OPENVIDU_SECRET}
livekit:
  api:
    key: ${LIVEKIT_API_KEY}
    secret: ${LIVEKIT_API_SECRET}