version: '3.8'
services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./altteul-fe:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - backend

  backend:
    image: gradle:8.6.0-jdk17
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./altteul-be:/app
      - gradle_cache:/home/gradle/.gradle
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/altteul
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/altteul
      - SPRING_REDIS_HOST=redis
    command: ./gradlew bootRun
    depends_on:
      - mysql
      - mongodb
      - redis

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=ssafy
      - MYSQL_DATABASE=altteul
      - MYSQL_USER=ssafy
      - MYSQL_PASSWORD=ssafy
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=altteul

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

volumes:
  mysql_dev_data:
  mongodb_dev_data:
  redis_dev_data:
  gradle_cache: